server:
  port: 4123

eureka:
  client:
    service-url:
      defaultZone: http://heaven:9lbr62wlprepohoqiruXedruDri2lnuVAz9@localhost:8761/eureka

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    compatibility-verifier:
      enabled: false
  application:
    name: '@name@'

management:
  endpoints:
    web:
      exposure:
        include: '*'
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
